version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest_network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb://mongodb:27017/chatroom
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - nest_network

volumes:
  mongodb_data:

networks:
  nest_network:
